






// Aligned with line numbers. LN - 10 = AP Item ID
pub enum APItems {
    Nothing,
    ProgressiveSword,
    SwordPedestal,
    Shovel,
    Boomerang,
    Map,
    Compass,
    Whistle,
    Burger,
    DarkStone,
    Hook,
    FishingRod,
    LavaTrinket,
    MisterHugs,
    Bombs,
    Shield,
    Nuke,
    Princess,
    Anvil,
    Strawberry,
    ShopCannon,
    CastleToShopCannon,
    DarkFortressCannon,
    CastleToDarkFortressCannon,
    DesertGeyserEast,
    DesertGeyserWest,
    VolcanoGeyser, 
    WaterfallGeyser,
    ElevatorButton,
    CallElevatorButtons,
    MirrorPortal,
    FairyPortal,
    Vine,
    OpenCastleFloor,
    FaceplantStone,
    SewerPipe,
    DarkStoneLeverLeft,
    DarkStoneLeverMiddle,
    DarkStoneLeverRight,
    Dragon,
    Shopkeeper,
    Mimic,
    King,
    Chicken,
    Elder,
    Boulder,
    Closet,
    PrincessStatue,
    PC,
    Dolphins,
    MimicPet,
    Gem,
    ChangeHeroName,
    ChangePrincessName,
    ChangeDarkLordName,
    JumpIncrease,
    SwordChest,
    Filler,
    Filler2,
    EventKillJuan,
    EventKillMiguel,
    EventKillJavi,
    EventKillAlberto,
    EventKillDaniel,
}